packages:
  - '.'
allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  netlify-cli: true
  sharp: true
  unix-dgram: true
supportedArchitectures:
  os:
    - linux
    - darwin
  cpu:
    - x64
    - arm64
  libc:
    - glibc
