/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lsenzdwjmiizpkqifatn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzZW56ZHdqbWlpenBrcWlmYXRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2NDc5MDQsImV4cCI6MjA4NzIyMzkwNH0.Ob3hQTZJwUVWsvKTg5X-ggFeNseYQKO7xD-zH1yNkPc"